CREATE TABLE IF NOT EXISTS
"sensors" ("id"  SERIAL , "username" VARCHAR(255) NOT NULL,
		   "password" VARCHAR(255) NOT NULL,
		   "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
		   "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), PRIMARY KEY ("id"));